name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add repositories
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt update
      - name: Install dependencies
        run: |
          sudo apt install libfftw3-dev libfftw3-3 vulkan-sdk
      - name: Build
        run: |
          mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build
          cmake -DCMAKE_BUILD_TYPE=RELEASE $GITHUB_WORKSPACE
          make
          sudo make install
